using Olve.Grids.Adjacencies;
using Olve.Grids.Grids;

namespace Olve.Grids.Generation.Sandbox;

public static class TileAdjacencies
{
    public static readonly (TileIndex From, TileIndex To, AdjacencyDirection Direction)[] Adjacencies =
    [
        // Tile 0
        (TileIndices.I0, TileIndices.I1, AdjacencyDirection.Right),
        (TileIndices.I0, TileIndices.I2, AdjacencyDirection.Right),
        (TileIndices.I0, TileIndices.I9, AdjacencyDirection.Right),
        (TileIndices.I0, TileIndices.I5, AdjacencyDirection.Down),
        (TileIndices.I0, TileIndices.I10, AdjacencyDirection.Down),
        (TileIndices.I0, TileIndices.I9, AdjacencyDirection.Down),
        (TileIndices.I0, TileIndices.I2, AdjacencyDirection.Left),
        (TileIndices.I0, TileIndices.I7, AdjacencyDirection.Left),
        (TileIndices.I0, TileIndices.I12, AdjacencyDirection.Left),
        (TileIndices.I0, TileIndices.I13, AdjacencyDirection.Left),
        (TileIndices.I0, TileIndices.I10, AdjacencyDirection.Up),
        (TileIndices.I0, TileIndices.I11, AdjacencyDirection.Up),
        (TileIndices.I0, TileIndices.I12, AdjacencyDirection.Up),
        (TileIndices.I0, TileIndices.I13, AdjacencyDirection.Up),
        
        // Tile 1
        (TileIndices.I1, TileIndices.I1, AdjacencyDirection.Right),
        (TileIndices.I1, TileIndices.I2, AdjacencyDirection.Right),
        (TileIndices.I1, TileIndices.I9, AdjacencyDirection.Right),
        (TileIndices.I1, TileIndices.I3, AdjacencyDirection.Down),
        (TileIndices.I1, TileIndices.I4, AdjacencyDirection.Down),
        (TileIndices.I1, TileIndices.I6, AdjacencyDirection.Down),
        (TileIndices.I1, TileIndices.I11, AdjacencyDirection.Down),
        (TileIndices.I1, TileIndices.I0, AdjacencyDirection.Left),
        (TileIndices.I1, TileIndices.I1, AdjacencyDirection.Left),
        (TileIndices.I1, TileIndices.I8, AdjacencyDirection.Left),
        (TileIndices.I1, TileIndices.I10, AdjacencyDirection.Up),
        (TileIndices.I1, TileIndices.I11, AdjacencyDirection.Up),
        (TileIndices.I1, TileIndices.I12, AdjacencyDirection.Up),
        (TileIndices.I1, TileIndices.I13, AdjacencyDirection.Up),
        
        // Tile 2
        (TileIndices.I2, TileIndices.I0, AdjacencyDirection.Right),
        (TileIndices.I2, TileIndices.I5, AdjacencyDirection.Right),
        (TileIndices.I2, TileIndices.I10, AdjacencyDirection.Right),
        (TileIndices.I2, TileIndices.I13, AdjacencyDirection.Right),
        (TileIndices.I2, TileIndices.I7, AdjacencyDirection.Down),
        (TileIndices.I2, TileIndices.I12, AdjacencyDirection.Down),
        (TileIndices.I2, TileIndices.I8, AdjacencyDirection.Down),
        (TileIndices.I2, TileIndices.I1, AdjacencyDirection.Left),
        (TileIndices.I2, TileIndices.I0, AdjacencyDirection.Left),
        (TileIndices.I2, TileIndices.I8, AdjacencyDirection.Left),
        (TileIndices.I2, TileIndices.I10, AdjacencyDirection.Up),
        (TileIndices.I2, TileIndices.I11, AdjacencyDirection.Up),
        (TileIndices.I2, TileIndices.I12, AdjacencyDirection.Up),
        (TileIndices.I2, TileIndices.I13, AdjacencyDirection.Up),
        
        // Tile 3
        (TileIndices.I3, TileIndices.I4, AdjacencyDirection.Right),
        (TileIndices.I3, TileIndices.I11, AdjacencyDirection.Right),
        (TileIndices.I3, TileIndices.I12, AdjacencyDirection.Right),
        (TileIndices.I3, TileIndices.I7, AdjacencyDirection.Down),
        (TileIndices.I3, TileIndices.I8, AdjacencyDirection.Down),
        (TileIndices.I3, TileIndices.I12, AdjacencyDirection.Down),
        (TileIndices.I3, TileIndices.I5, AdjacencyDirection.Left),
        (TileIndices.I3, TileIndices.I6, AdjacencyDirection.Left),
        (TileIndices.I3, TileIndices.I4, AdjacencyDirection.Left),
        (TileIndices.I3, TileIndices.I9, AdjacencyDirection.Left),
        (TileIndices.I3, TileIndices.I1, AdjacencyDirection.Up),
        (TileIndices.I3, TileIndices.I6, AdjacencyDirection.Up),
        (TileIndices.I3, TileIndices.I8, AdjacencyDirection.Up),
        (TileIndices.I3, TileIndices.I9, AdjacencyDirection.Up),
        
        // Tile 4
        (TileIndices.I4, TileIndices.I3, AdjacencyDirection.Right),
        (TileIndices.I4, TileIndices.I6, AdjacencyDirection.Right),
        (TileIndices.I4, TileIndices.I7, AdjacencyDirection.Right),
        (TileIndices.I4, TileIndices.I8, AdjacencyDirection.Right),
        (TileIndices.I4, TileIndices.I9, AdjacencyDirection.Down),
        (TileIndices.I4, TileIndices.I5, AdjacencyDirection.Down),
        (TileIndices.I4, TileIndices.I10, AdjacencyDirection.Down),
        (TileIndices.I4, TileIndices.I3, AdjacencyDirection.Left),
        (TileIndices.I4, TileIndices.I10, AdjacencyDirection.Left),
        (TileIndices.I4, TileIndices.I11, AdjacencyDirection.Left),
        (TileIndices.I4, TileIndices.I1, AdjacencyDirection.Up),
        (TileIndices.I4, TileIndices.I6, AdjacencyDirection.Up),
        (TileIndices.I4, TileIndices.I8, AdjacencyDirection.Up),
        (TileIndices.I4, TileIndices.I9, AdjacencyDirection.Up),
        
        // Tile 5
        (TileIndices.I5, TileIndices.I3, AdjacencyDirection.Right),
        (TileIndices.I5, TileIndices.I6, AdjacencyDirection.Right),
        (TileIndices.I5, TileIndices.I7, AdjacencyDirection.Right),
        (TileIndices.I5, TileIndices.I8, AdjacencyDirection.Right),
        (TileIndices.I5, TileIndices.I9, AdjacencyDirection.Down),
        (TileIndices.I5, TileIndices.I10, AdjacencyDirection.Down),
        (TileIndices.I5, TileIndices.I5, AdjacencyDirection.Down),
        (TileIndices.I5, TileIndices.I2, AdjacencyDirection.Left),
        (TileIndices.I5, TileIndices.I7, AdjacencyDirection.Left),
        (TileIndices.I5, TileIndices.I12, AdjacencyDirection.Left),
        (TileIndices.I5, TileIndices.I13, AdjacencyDirection.Left),
        (TileIndices.I5, TileIndices.I0, AdjacencyDirection.Up),
        (TileIndices.I5, TileIndices.I4, AdjacencyDirection.Up),
        (TileIndices.I5, TileIndices.I5, AdjacencyDirection.Up),
        
        // Tile 6
        (TileIndices.I6, TileIndices.I7, AdjacencyDirection.Right),
        (TileIndices.I6, TileIndices.I3, AdjacencyDirection.Right),
        (TileIndices.I6, TileIndices.I8, AdjacencyDirection.Right),
        (TileIndices.I6, TileIndices.I6, AdjacencyDirection.Right),
        (TileIndices.I6, TileIndices.I11, AdjacencyDirection.Down),
        (TileIndices.I6, TileIndices.I6, AdjacencyDirection.Down),
        (TileIndices.I6, TileIndices.I3, AdjacencyDirection.Down),
        (TileIndices.I6, TileIndices.I4, AdjacencyDirection.Down),
        (TileIndices.I6, TileIndices.I5, AdjacencyDirection.Left),
        (TileIndices.I6, TileIndices.I4, AdjacencyDirection.Left),
        (TileIndices.I6, TileIndices.I9, AdjacencyDirection.Left),
        (TileIndices.I6, TileIndices.I6, AdjacencyDirection.Left),
        (TileIndices.I6, TileIndices.I1, AdjacencyDirection.Up),
        (TileIndices.I6, TileIndices.I6, AdjacencyDirection.Up),
        (TileIndices.I6, TileIndices.I8, AdjacencyDirection.Up),
        (TileIndices.I6, TileIndices.I9, AdjacencyDirection.Up),

        // Tile 7
        (TileIndices.I7, TileIndices.I0, AdjacencyDirection.Right),
        (TileIndices.I7, TileIndices.I5, AdjacencyDirection.Right),
        (TileIndices.I7, TileIndices.I10, AdjacencyDirection.Right),
        (TileIndices.I7, TileIndices.I13, AdjacencyDirection.Right),
        (TileIndices.I7, TileIndices.I7, AdjacencyDirection.Down),
        (TileIndices.I7, TileIndices.I12, AdjacencyDirection.Down),
        (TileIndices.I7, TileIndices.I8, AdjacencyDirection.Down),
        (TileIndices.I7, TileIndices.I6, AdjacencyDirection.Left),
        (TileIndices.I7, TileIndices.I9, AdjacencyDirection.Left),
        (TileIndices.I7, TileIndices.I4, AdjacencyDirection.Left),
        (TileIndices.I7, TileIndices.I5, AdjacencyDirection.Left),
        (TileIndices.I7, TileIndices.I2, AdjacencyDirection.Up),
        (TileIndices.I7, TileIndices.I7, AdjacencyDirection.Up),
        (TileIndices.I7, TileIndices.I3, AdjacencyDirection.Up),

        // Tile 8
        (TileIndices.I8, TileIndices.I9, AdjacencyDirection.Right),
        (TileIndices.I8, TileIndices.I1, AdjacencyDirection.Right),
        (TileIndices.I8, TileIndices.I2, AdjacencyDirection.Right),
        (TileIndices.I8, TileIndices.I6, AdjacencyDirection.Down),
        (TileIndices.I8, TileIndices.I3, AdjacencyDirection.Down),
        (TileIndices.I8, TileIndices.I4, AdjacencyDirection.Down),
        (TileIndices.I8, TileIndices.I11, AdjacencyDirection.Down),
        (TileIndices.I8, TileIndices.I5, AdjacencyDirection.Left),
        (TileIndices.I8, TileIndices.I6, AdjacencyDirection.Left),
        (TileIndices.I8, TileIndices.I4, AdjacencyDirection.Left),
        (TileIndices.I8, TileIndices.I9, AdjacencyDirection.Left),
        (TileIndices.I8, TileIndices.I3, AdjacencyDirection.Up),
        (TileIndices.I8, TileIndices.I7, AdjacencyDirection.Up),
        (TileIndices.I8, TileIndices.I2, AdjacencyDirection.Up),

        // Tile 9
        (TileIndices.I9, TileIndices.I6, AdjacencyDirection.Right),
        (TileIndices.I9, TileIndices.I7, AdjacencyDirection.Right),
        (TileIndices.I9, TileIndices.I3, AdjacencyDirection.Right),
        (TileIndices.I9, TileIndices.I8, AdjacencyDirection.Right),
        (TileIndices.I9, TileIndices.I6, AdjacencyDirection.Down),
        (TileIndices.I9, TileIndices.I3, AdjacencyDirection.Down),
        (TileIndices.I9, TileIndices.I4, AdjacencyDirection.Down),
        (TileIndices.I9, TileIndices.I11, AdjacencyDirection.Down),
        (TileIndices.I9, TileIndices.I8, AdjacencyDirection.Left),
        (TileIndices.I9, TileIndices.I1, AdjacencyDirection.Left),
        (TileIndices.I9, TileIndices.I0, AdjacencyDirection.Left),
        (TileIndices.I9, TileIndices.I4, AdjacencyDirection.Up),
        (TileIndices.I9, TileIndices.I5, AdjacencyDirection.Up),
        (TileIndices.I9, TileIndices.I0, AdjacencyDirection.Up),

        
        // Tile 10
        (TileIndices.I10, TileIndices.I11, AdjacencyDirection.Right),
        (TileIndices.I10, TileIndices.I12, AdjacencyDirection.Right),
        (TileIndices.I10, TileIndices.I4, AdjacencyDirection.Right),
        (TileIndices.I10, TileIndices.I0, AdjacencyDirection.Down),
        (TileIndices.I10, TileIndices.I1, AdjacencyDirection.Down),
        (TileIndices.I10, TileIndices.I2, AdjacencyDirection.Down),
        (TileIndices.I10, TileIndices.I13, AdjacencyDirection.Down),
        (TileIndices.I10, TileIndices.I2, AdjacencyDirection.Left),
        (TileIndices.I10, TileIndices.I7, AdjacencyDirection.Left),
        (TileIndices.I10, TileIndices.I12, AdjacencyDirection.Left),
        (TileIndices.I10, TileIndices.I13, AdjacencyDirection.Left),
        (TileIndices.I10, TileIndices.I5, AdjacencyDirection.Up),
        (TileIndices.I10, TileIndices.I0, AdjacencyDirection.Up),
        (TileIndices.I10, TileIndices.I4, AdjacencyDirection.Up),

        // Tile 11
        (TileIndices.I11, TileIndices.I12, AdjacencyDirection.Right),
        (TileIndices.I11, TileIndices.I11, AdjacencyDirection.Right),
        (TileIndices.I11, TileIndices.I4, AdjacencyDirection.Right),
        (TileIndices.I11, TileIndices.I0, AdjacencyDirection.Down),
        (TileIndices.I11, TileIndices.I1, AdjacencyDirection.Down),
        (TileIndices.I11, TileIndices.I2, AdjacencyDirection.Down),
        (TileIndices.I11, TileIndices.I13, AdjacencyDirection.Down),
        (TileIndices.I11, TileIndices.I10, AdjacencyDirection.Left),
        (TileIndices.I11, TileIndices.I11, AdjacencyDirection.Left),
        (TileIndices.I11, TileIndices.I3, AdjacencyDirection.Left),
        (TileIndices.I11, TileIndices.I1, AdjacencyDirection.Up),
        (TileIndices.I11, TileIndices.I6, AdjacencyDirection.Up),
        (TileIndices.I11, TileIndices.I8, AdjacencyDirection.Up),
        (TileIndices.I11, TileIndices.I9, AdjacencyDirection.Up),

        // Tile 12
        (TileIndices.I12, TileIndices.I0, AdjacencyDirection.Right),
        (TileIndices.I12, TileIndices.I5, AdjacencyDirection.Right),
        (TileIndices.I12, TileIndices.I10, AdjacencyDirection.Right),
        (TileIndices.I12, TileIndices.I13, AdjacencyDirection.Right),
        (TileIndices.I12, TileIndices.I0, AdjacencyDirection.Down),
        (TileIndices.I12, TileIndices.I1, AdjacencyDirection.Down),
        (TileIndices.I12, TileIndices.I2, AdjacencyDirection.Down),
        (TileIndices.I12, TileIndices.I13, AdjacencyDirection.Down),
        (TileIndices.I12, TileIndices.I10, AdjacencyDirection.Left),
        (TileIndices.I12, TileIndices.I11, AdjacencyDirection.Left),
        (TileIndices.I12, TileIndices.I3, AdjacencyDirection.Left),
        (TileIndices.I12, TileIndices.I2, AdjacencyDirection.Up),
        (TileIndices.I12, TileIndices.I7, AdjacencyDirection.Up),
        (TileIndices.I12, TileIndices.I3, AdjacencyDirection.Up),
        
        // Tile 13
        (TileIndices.I13, TileIndices.I0, AdjacencyDirection.Right),
        (TileIndices.I13, TileIndices.I5, AdjacencyDirection.Right),
        (TileIndices.I13, TileIndices.I10, AdjacencyDirection.Right),
        (TileIndices.I13, TileIndices.I13, AdjacencyDirection.Right),
        (TileIndices.I13, TileIndices.I0, AdjacencyDirection.Down),
        (TileIndices.I13, TileIndices.I1, AdjacencyDirection.Down),
        (TileIndices.I13, TileIndices.I2, AdjacencyDirection.Down),
        (TileIndices.I13, TileIndices.I13, AdjacencyDirection.Down),
        (TileIndices.I13, TileIndices.I2, AdjacencyDirection.Left),
        (TileIndices.I13, TileIndices.I7, AdjacencyDirection.Left),
        (TileIndices.I13, TileIndices.I12, AdjacencyDirection.Left),
        (TileIndices.I13, TileIndices.I13, AdjacencyDirection.Left),
        (TileIndices.I13, TileIndices.I10, AdjacencyDirection.Up),
        (TileIndices.I13, TileIndices.I11, AdjacencyDirection.Up),
        (TileIndices.I13, TileIndices.I12, AdjacencyDirection.Up),
        (TileIndices.I13, TileIndices.I13, AdjacencyDirection.Up),
    ];
}