name: 'Get Version 📦 (Linux/macOS)'
description: 'Gets the version from the VERSION file'
inputs:
  pre-release:
    description: 'Indicates if the version is a pre-release'
    required: true
  directory:
    description: 'The directory to load the version from'
    required: true

outputs:
  version:
    description: Version number
    value: ${{ steps.version.outputs.VERSION }}

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: ./.github/actions/python-setup
      with:
        directory: ${{ inputs.directory }}

    - if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      name: Load version
      id: version
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        VERSION=$(uv run version ${{ inputs.pre-release == 'true' && '--prerelease' || ''}})
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Version loaded: $VERSION"
