name: Publish Olve.Grids

on:
  push:
    branches:
      - "**"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "**"

env:
  VERSION: 1.0.0

defaults:
  run:
    working-directory: .

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Version Variable
        if: ${{ github.ref_type == 'tag' }}
        env:
          TAG: ${{ github.ref_name }}
        run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Debug Version
        run: echo "VERSION=$VERSION"
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore -c Release
      
      - name: Test
        run: dotnet test --no-build -c Release --verbosity normal
  
  nuget-grids:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Olve.Grids
    needs:
      - test
    steps:
      - uses: actions/checkout@v3

      - name: Set Version Variable
        if: ${{ github.ref_type == 'tag' }}
        env:
          TAG: ${{ github.ref_name }}
        run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Debug Version
        run: echo "VERSION=$VERSION"

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release /p:Version=$VERSION

      - name: pack nuget packages
        run: dotnet pack --output nupkgs --no-restore --no-build -c Release /p:PackageVersion=$VERSION

      - name: upload nuget package
        if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
        run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
  
  nuget-grids-debroglie:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Olve.Grids.DeBroglie
    needs:
      - test
    steps:
      - uses: actions/checkout@v3

      - name: Set Version Variable
        if: ${{ github.ref_type == 'tag' }}
        env:
          TAG: ${{ github.ref_name }}
        run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Debug Version
        run: echo "VERSION=$VERSION"

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release /p:Version=$VERSION

      - name: pack nuget packages
        run: dotnet pack --output nupkgs --no-restore --no-build -c Release /p:PackageVersion=$VERSION

      - name: upload nuget package
        if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
        run: dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        
  publish:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src/Demo
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
        
      - name: Set Version Variable
        if: ${{ github.ref_type == 'tag' }}
        env:
          TAG: ${{ github.ref_name }}
        run: |
          $VERSION="${{ env.TAG }}".Substring(1)
          echo "VERSION=${VERSION}" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "Version set to: ${VERSION}"

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release "/p:Version=${{ env.VERSION }}" /p:DebugType=None /p:DebugSymbols=false -r win-x64

      - name: publish demo as executable
        run: dotnet publish --output ./build --no-restore --no-build -c Release -r win-x64 /p:PackageVersion=${{ env.VERSION }}
        
      - name: list files
        run: ls build

      - name: Zip Demo
        run: |
          Compress-Archive -Path build\* -DestinationPath demo-${{ env.VERSION }}.zip

      - name: upload demo
        if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: Demo-${{ env.VERSION }}
          path: demo-${{ env.VERSION }}.zip
  